export const quiz = {
    state: () => ({
        rightAnswers: 0,
        totalAnswers: 0,
        questions: [
            {
                question: 'Что выведет код ниже?',
                firstAnswer: 'NaN',
                secondAnswer: '100',
                thirdAnswer: '-100',
                fourthAnswer: '10',
                id: 1,
            },
            {
                question: 'Что выведет код ниже?',
                firstAnswer: 'NaN',
                secondAnswer: '3',
                thirdAnswer: '4',
                fourthAnswer: 'В коде ошибка',
                id: 2,
            },
            {
                question: 'Что выведет код ниже?',
                firstAnswer: 'lice',
                secondAnswer: 'ice',
                thirdAnswer: 'ice me',
                fourthAnswer: ':)',
                id: 3,
            },
            {
                question: 'Что из приведенного ниже не равно indefined?',
                firstAnswer: '1 и 2',
                secondAnswer: 'только 1',
                thirdAnswer: 'только 2',
                fourthAnswer: 'оба выведут true',
                id: 4,
            },
            {
                question: 'В чем отличие func.call от func.apply?',
                firstAnswer: 'func.call ожидает список аргументов, в то время как func.apply принимает псевдомассив',
                secondAnswer: 'func.apply ожидает список аргументов, в то время как func.call принимает псевдомассив',
                thirdAnswer: 'func.call можно использовать только внутри функции',
                fourthAnswer: 'func.apply можно использовать только внутри функции',
                id: 5,
            },
            {
                question: 'Ключевое слово «extends»',
                firstAnswer: 'Проверяет есть ли свойство в обьекте',
                secondAnswer: 'Проверяет есть ли заданное свойство в классе',
                thirdAnswer: 'Проверяет есть ли заданное свойство в функции',
                fourthAnswer: 'Используются для наследования классов',
                id: 6,
            },
            {
                question: 'В чем отличие Promise.all от Promise.allSettled?',
                firstAnswer: 'Promise.all возвращает новый промис, а Promise.allSettled - массив обьектов',
                secondAnswer: 'Promise.all синтаксический сахар для Promise.allSettled',
                thirdAnswer: 'Promise.all принимает только массивы, а Promise.allSettled - только обьекты',
                fourthAnswer: 'Promise.allSettled принимает только массивы, а Promise.all - только обьекты',
                id: 7,
            },

            {
                question: 'На какой строчке кода появится ошибка?',
                firstAnswer: 'Здесь нет ошибки',
                secondAnswer: 'На 1',
                thirdAnswer: 'На 2',
                fourthAnswer: 'На 3',
                id: 8,
            },
            {
                question: 'Что нужно написать в переменную regexp чтобы получить содержимое str?',
                firstAnswer: '/w+\\w+\\w+\\w+\\w+/g',
                secondAnswer: '/\w+{5}/g',
                thirdAnswer: '/\\w+/g',
                fourthAnswer: '/\\w+{all}/g',
                id: 9,
            },
            {
                question: 'JavaScript - ',
                firstAnswer: 'Статически типизированный язык',
                secondAnswer: 'Статически нетипизированный язык',
                thirdAnswer: 'Динамически типизированный язык',
                fourthAnswer: 'Динамически нетипизированный язык',
                id: 10,
            },
            {
                question: 'Продолжите фразу: Для var не существует',
                firstAnswer: 'средней области видимости',
                secondAnswer: 'блочной области видимости',
                thirdAnswer: 'внутренней области видимости',
                fourthAnswer: 'внешней области видимости',
                id: 11,
            },
            {
                question: 'Бинарным называется оператор',
                firstAnswer: 'который применяется к одному операнду',
                secondAnswer: 'который применяется к бинарному типу данных',
                thirdAnswer: 'который применяется к двум операндам',
                fourthAnswer: 'который применяется к методам',
                id: 12,
            },
            {
                question: 'В какой строке вызов alert покажет true?',
                firstAnswer: 'Только в 1',
                secondAnswer: 'В 1 и в 3',
                thirdAnswer: 'ни в какой',
                fourthAnswer: 'Во всех случаях результат будет true',
                id: 13,
            },
            {
                question: '__proto__ - это',
                firstAnswer: 'метод',
                secondAnswer: 'свойство',
                thirdAnswer: 'обьект',
                fourthAnswer: 'класс',
                id: 14,
            },
            {
                question: 'Скрипты с defer всегда выполняются',
                firstAnswer: 'до события DOMContentLoaded',
                secondAnswer: 'после события DOMContentLoaded',
                thirdAnswer: 'во время DOMContentLoaded',
                fourthAnswer: 'во всех случаях',
                id: 15,
            },

        ]
    }),
    namespaced: true,
};